### ISSUE TITLE
Any way to ident using tabs instead of spaces?

### ISSUE THREAD

**Issue by stopiccot** [rubysl/rubysl-rexml#3]
Any way to ident using tabs instead of spaces?

**Comment by jemc** [comment]
@stopiccot - can you clarify your question?

I'm not sure what you're asking, but know that this repository's source code is simply synced to that of the MRI implementation, so if you have an issue with the implementation, you should try filing at MRI's issue tracker: https://bugs.ruby-lang.org/.

**Comment by YorickPeterse** [comment]
As @jemc mentioned, please report any (meaningful) issues to https://bugs.ruby-lang.org/ as we simply vendor the code as a Gem.
